create_clock -period 5.000 -name clk_pin_p -waveform {0.000 2.500} [get_ports clk_pin_p]
set_input_delay -clock [get_clocks clk_pin_p] 0.000 [get_ports {rst_pin rxd_pin btn_pin}]
set_input_delay -clock [get_clocks clk_pin_p] -min -0.500 [get_ports {rst_pin rxd_pin btn_pin}]
set_output_delay -clock [get_clocks clk_pin_p] -4.000 [get_ports led_pins*]
set_output_delay -clock [get_clocks clk_pin_p] -min -0.500 [get_ports led_pins*]

set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led_pins[3]}]
set_property DRIVE 12 [get_ports {led_pins[0]}]
set_property DRIVE 12 [get_ports {led_pins[1]}]
set_property DRIVE 12 [get_ports {led_pins[2]}]
set_property DRIVE 12 [get_ports {led_pins[3]}]
set_property SLEW SLOW [get_ports {led_pins[0]}]
set_property SLEW SLOW [get_ports {led_pins[1]}]
set_property SLEW SLOW [get_ports {led_pins[2]}]
set_property SLEW SLOW [get_ports {led_pins[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_pins[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_pins[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_pins[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led_pins[7]}]
set_property DRIVE 12 [get_ports {led_pins[4]}]
set_property DRIVE 12 [get_ports {led_pins[5]}]
set_property DRIVE 12 [get_ports {led_pins[6]}]
set_property DRIVE 12 [get_ports {led_pins[7]}]
set_property SLEW SLOW [get_ports {led_pins[4]}]
set_property SLEW SLOW [get_ports {led_pins[5]}]
set_property SLEW SLOW [get_ports {led_pins[6]}]
set_property SLEW SLOW [get_ports {led_pins[7]}]
set_property IOSTANDARD LVDS [get_ports clk_pin_p]
set_property IOSTANDARD LVCMOS15 [get_ports rst_pin]
set_property IOSTANDARD LVCMOS25 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS25 [get_ports btn_pin]

set_property PACKAGE_PIN AD12 [get_ports clk_pin_p]
set_property PACKAGE_PIN AD11 [get_ports clk_pin_n]
set_property PACKAGE_PIN AB8 [get_ports {led_pins[0]}]
set_property PACKAGE_PIN AA8 [get_ports {led_pins[1]}]
set_property PACKAGE_PIN AC9 [get_ports {led_pins[2]}]
set_property PACKAGE_PIN AB9 [get_ports {led_pins[3]}]
set_property PACKAGE_PIN AE26 [get_ports {led_pins[4]}]
set_property PACKAGE_PIN G19 [get_ports {led_pins[5]}]
set_property PACKAGE_PIN E18 [get_ports {led_pins[6]}]
set_property PACKAGE_PIN F16 [get_ports {led_pins[7]}]
set_property PACKAGE_PIN AB7 [get_ports rst_pin]
set_property PACKAGE_PIN M19 [get_ports rxd_pin]
set_property PACKAGE_PIN Y29 [get_ports btn_pin]

set_property IOB TRUE [all_fanin -only_cells -startpoints_only -flat [all_outputs]]